name: Deploy to Production Aula DevOps

# Definir os gatilhos para o workflow
on:
  push:
    branches:
      - master

# Configuração dos jobs do workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Executar testes
      - name: Run tests
        run: mvn test

      # 4. Compilar a aplicação
      - name: Build the application
        run: mvn package

      # 5. Configurar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # 6. Configurar credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 7. Inicializar Terraform
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 8. Verificar o plano de infraestrutura
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      # 9. Criar infraestrutura
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve